@SET PB="C:\Program Files\PureBasic\Compilers\pbcompiler.exe"
@SET COMP=%PB% /check /quiet

%COMP% demos/001/"001 Textured rotating cube (210).pb"
%COMP% demos/002/"002 Render text and generate textures (210).pb"
%COMP% demos/003/"003 Textured rotating cube (330).pb"
%COMP% demos/004/"004 Model, View, Projection, and LookAt (330).pb"
%COMP% demos/005/"005 FPS Camera, Sampler2D arrays, mouse (330).pb"
%COMP% demos/006/"006 ArcBall Camera (330).pb"
%COMP% demos/007/"007 Array Textures (330).pb"
%COMP% demos/008/"008 Phong ligthing (330).pb"
%COMP% demos/009/"009 Phong, materials, specular map (330).pb"
%COMP% demos/010/"010 Emissive and Normal maps (330).pb"
%COMP% demos/011/"011 Decals (330).pb"
%COMP% demos/012/"012 Dynamic shader instead of a texture (330).pb"
%COMP% demos/013/"013 Render to Texture (330).pb"

%COMP% examples/"001 Minimal.pb"
%COMP% examples/"002 Almost minimal.pb"
%COMP% examples/"003 Callbacks.pb"
%COMP% examples/"004 Borderless full screen window.pb"
%COMP% examples/"005 Switch between windowed and full screen.pb"
%COMP% examples/"006 Modern OpenGL debug output.pb"
%COMP% examples/"007 SysInfo.pb"
%COMP% examples/"008 Timers 01.pb"
%COMP% examples/"009 Timers 02.pb"
%COMP% examples/"010 Timers 03.pb"
%COMP% examples/"011 How to take a screenshot.pb"
%COMP% examples/"012 Old-style error checking.pb"
%COMP% examples/"013 VBO + VAO + shaders (330).pb"
%COMP% examples/"014 Using shaders with legacy OpenGL (210).pb"
%COMP% examples/"015 Draw two triangles (VBO + VAO) (330).pb"
%COMP% examples/"016 Draw two triangles using indices (330).pb"
%COMP% examples/"017 Using uniforms to pass parameters to a shader (330).pb"
%COMP% examples/"018 FPS and Frame Time.pb"
%COMP% examples/"019 KeyBoard input.pb"
%COMP% examples/"020 Triangle with interpolated colors (330).pb"
%COMP% examples/"021 Triangle interpolated but using one VBO (330).pb"
%COMP% examples/"022 Sample a texture (330).pb"
%COMP% examples/"023 Translation using a matrix (330).pb"
%COMP% examples/"024 Sample and mix two textures (330).pb"
%COMP% examples/"025 Rotate textured quad using matrices (330).pb"

%COMP% extras/"Batch/test_quads.pb"
%COMP% extras/"Batch/test_textured_quads.pb"
%COMP% extras/"Batch_ AT/test_quads.pb"
%COMP% extras/"Batch_ AT/test_textured_quads.pb"
%COMP% extras/"Fonts/001 Render Unicode text.pb"
%COMP% extras/"Fonts/002 Font viewer.pb"
%COMP% extras/"Fonts/003 Render text using BMF files.pb"
%COMP% extras/"Fonts/004 BMF arial-unicode-12.pb"
%COMP% extras/"Fonts/005 BMF videophreak-16.pb"
%COMP% extras/"Fonts/006 BMF gimp-42.pb"
%COMP% extras/"RenderText/test.pb"
%COMP% extras/"RenderText_210/test.pb"
%COMP% extras/"RenderText_B/test.pb"
%COMP% extras/"RenderText_BAT/test.pb"
%COMP% extras/"Vertex Array Object/test.pb"
%COMP% extras/"IMGUI/test fixed gui.pb"
%COMP% extras/"IMGUI/test movable gui.pb"
pause
